/// Pairs trading models — PairPosition, PairSignal, PairDirection.
///
/// A pair trade consists of two linked Position legs (long A / short B, or vice versa).
/// Opening and closing are atomic: both legs open together, both close together.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Direction of a pair trade.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PairDirection {
    /// Long asset A, short asset B (spread too low, expect it to rise)
    LongAShortB,
    /// Short asset A, long asset B (spread too high, expect it to fall)
    ShortALongB,
}

impl PairDirection {
    pub fn leg_side(&self, is_leg_a: bool) -> &'static str {
        match (self, is_leg_a) {
            (PairDirection::LongAShortB, true) => "long",
            (PairDirection::LongAShortB, false) => "short",
            (PairDirection::ShortALongB, true) => "short",
            (PairDirection::ShortALongB, false) => "long",
        }
    }
}

/// Signal generated by the pairs strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairSignal {
    /// Whether to enter, exit, or do nothing
    pub action: PairAction,
    /// Direction of the pair trade (only set on entry)
    pub direction: Option<PairDirection>,
    /// Z-score at signal time
    pub zscore: f64,
    /// Spread value log(price_a / price_b)
    pub spread: f64,
    /// Current day index (bars since start)
    pub day_index: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PairAction {
    /// No action needed
    Hold,
    /// Enter a new pair trade (direction set)
    Enter,
    /// Exit current pair trade (take profit — spread reverted to mean)
    ExitTakeProfit,
    /// Exit current pair trade (stop loss — spread diverged further)
    ExitStopLoss,
    /// Exit current pair trade (max hold exceeded)
    ExitMaxHold,
}

impl PairSignal {
    pub fn is_exit(&self) -> bool {
        matches!(self.action, PairAction::ExitTakeProfit | PairAction::ExitStopLoss | PairAction::ExitMaxHold)
    }

    pub fn is_entry(&self) -> bool {
        self.action == PairAction::Enter
    }
}

/// Active pair trade state — persisted to survive restarts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairState {
    /// Unique pair trade ID
    pub id: String,
    /// Pair label (e.g., "SHIB/UNI")
    pub pair_label: String,
    /// Asset A symbol (e.g., "SHIBUSDT")
    pub symbol_a: String,
    /// Asset B symbol (e.g., "UNIUSDT")
    pub symbol_b: String,
    /// Direction of the trade
    pub direction: PairDirection,
    /// Position ID for leg A
    pub leg_a_id: String,
    /// Position ID for leg B
    pub leg_b_id: String,
    /// Entry z-score
    pub entry_zscore: f64,
    /// Entry spread
    pub entry_spread: f64,
    /// Entry day index
    pub entry_day: usize,
    /// Entry price of asset A
    pub entry_price_a: f64,
    /// Entry price of asset B
    pub entry_price_b: f64,
    /// When the trade was entered
    pub created_at: DateTime<Utc>,
    /// Status: "open" or "closed"
    pub status: String,
}

impl PairState {
    pub fn new(
        pair_label: &str,
        symbol_a: &str,
        symbol_b: &str,
        direction: PairDirection,
        leg_a_id: &str,
        leg_b_id: &str,
        entry_zscore: f64,
        entry_spread: f64,
        entry_day: usize,
        entry_price_a: f64,
        entry_price_b: f64,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            pair_label: pair_label.to_string(),
            symbol_a: symbol_a.to_string(),
            symbol_b: symbol_b.to_string(),
            direction,
            leg_a_id: leg_a_id.to_string(),
            leg_b_id: leg_b_id.to_string(),
            entry_zscore,
            entry_spread,
            entry_day,
            entry_price_a,
            entry_price_b,
            created_at: Utc::now(),
            status: "open".to_string(),
        }
    }
}
