/// Signal model and direction enum.

use serde::{Deserialize, Serialize};

/// Signal direction enumeration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SignalDirection {
    Long,
    Short,
    Neutral,
    Exit,
}

/// Trading signal generated by strategies.
#[derive(Debug, Clone)]
pub struct Signal {
    pub id: Option<String>,
    pub symbol: String,
    pub exchange: String,
    pub direction: SignalDirection,
    pub strength: f64,
    pub confidence: f64,
    pub price: f64,
    pub strategy_id: String,
    pub regime: Option<String>,
    pub risk_verdict: Option<String>,
}

impl Signal {
    /// Whether the signal is strong enough to act on.
    pub fn is_actionable(&self) -> bool {
        self.strength >= 0.3 && self.confidence >= 0.2
    }
}

/// A single sub-signal from one signal type.
#[derive(Debug, Clone)]
pub struct SubSignal {
    pub direction: SignalDirection,
    pub strength: f64,
    pub source: String, // "breakout", "mean_reversion", "trend", "vwap", "divergence"
}
