"""Signal model for strategy-generated trading signals."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
from enum import Enum


class SignalDirection(Enum):
    """Signal direction enumeration."""

    LONG = "long"
    SHORT = "short"
    NEUTRAL = "neutral"
    EXIT = "exit"


@dataclass
class Signal:
    """Signal model for strategy-generated trading signals.

    Generated by strategies and consumed by the execution engine.
    Includes strength prediction from neural net if available.

    """

    id: Optional[str] = None
    symbol: str = ""
    exchange: str = ""
    direction: SignalDirection = SignalDirection.NEUTRAL
    strength: float = 0.0  # 0-1, neural net prediction
    confidence: float = 0.0  # 0-1, model confidence
    price: float = 0.0
    quantity: float = 0.0  # suggested position size
    strategy_id: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    features: Optional[dict] = None  # raw features for training
    predicted_outcome: Optional[float] = None  # neural net predicted return

    @property
    def is_actionable(self) -> bool:
        """Check if signal is strong enough to act on."""
        return self.strength >= 0.5 and self.confidence >= 0.4

    @property
    def urgency(self) -> str:
        """Categorize signal urgency."""
        if self.strength >= 0.8:
            return "high"
        elif self.strength >= 0.6:
            return "medium"
        return "low"

    def to_dict(self) -> dict:
        """Convert signal to dictionary for storage."""
        return {
            "id": self.id,
            "symbol": self.symbol,
            "exchange": self.exchange,
            "direction": self.direction.value,
            "strength": self.strength,
            "confidence": self.confidence,
            "price": self.price,
            "quantity": self.quantity,
            "strategy_id": self.strategy_id,
            "timestamp": self.timestamp.isoformat(),
            "predicted_outcome": self.predicted_outcome,
        }
